export const routes = {
  home: "/",
  products: "/products",
  shop: "/products",
  cart: "/cart",
  wishlist: "/wishlist",
  checkout: "/checkout",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  profile: "/profile",
  account: "/profile",
  about: "/about",
  contact: "/contact",
  admin: {
    root: "/admin",
    products: "/admin/products",
    orders: "/admin/orders",
    customers: "/admin/customers",
    settings: "/admin/settings",
  },
} as const;
