export const routes = {
  home: "/",
  products: "/products",
  shop: "/products",
  cart: "/cart",
  wishlist: "/wishlist",
  orderSuccess: (id: string) => `/order-success/${id}`,
  checkout: "/checkout",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  profile: "/profile",
  profileOrder: (id: string) => `/profile/orders/${id}`,
  account: "/profile",
  authRedirect: "/auth/redirect",
  about: "/about",
  contact: "/contact",
  admin: {
    root: "/admin",
    products: "/admin/products",
    productsNew: "/admin/products/new",
    productEdit: (id: string) => `/admin/products/${id}/edit`,
    categories: "/admin/categories",
    brands: "/admin/brands",
    orders: "/admin/orders",
    orderDetail: (id: string) => `/admin/orders/${id}`,
    inventory: "/admin/inventory",
    users: "/admin/users",
    banners: "/admin/banners",
    coupons: "/admin/coupons",
    reviews: "/admin/reviews",
    settings: "/admin/settings",
    customers: "/admin/users",
  },
} as const;
